# Generated by Django 2.2.7 on 2020-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neuralNetworkFile', models.FileField(upload_to='')),
                ('usernameSender', models.CharField(max_length=50)),
                ('jsonNeuralNetwork', models.CharField(max_length=10000)),
                ('numberOfGenerations', models.IntegerField()),
                ('currentGeneration', models.IntegerField()),
                ('rewardPoints', models.IntegerField()),
                ('minAccuracy', models.FloatField()),
                ('weightsFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=33)),
                ('email', models.CharField(max_length=50)),
                ('joinDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=33)),
                ('email', models.CharField(max_length=50)),
                ('joinDate', models.DateField()),
                ('listening', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
